import type { Metadata } from "next";
import ogImage from "./jaeyguides-social.png";
import faviconPng from "./favicon.png";

export const metadata: Metadata = {
  title: {
    default: "JaeyGuides — PDF & Image Utilities",
    template: "%s — JaeyGuides",
  },
  description:
    "Fast, private, in-browser PDF and image tools. Merge PDFs, resize images, convert formats, and more - all processed locally in your browser.",
  keywords: [
    "PDF tools",
    "image tools",
    "file converter",
    "PDF merge",
    "image resize",
    "online tools",
    "PDF compressor",
    "image converter",
    "WebP converter",
    // additional long-tail and high-value keywords for SEO
    "compress pdf online",
    "online pdf compressor",
    "reduce pdf size",
    "pdf optimizer",
    "compress pdf",
    "optimize pdf",
    "image compressor online",
    "compress images",
    "optimize images for web",
    "convert image to webp",
    "jpg to png",
    "png to jpg",
    "image format converter",
    "resize image online",
    "online image converter",
    "client-side tools",
    "privacy-first tools",
    "in-browser conversion",
    "offline image converter",
    "bulk image converter",
    "batch image processing",
    "pdf split",
    "pdf to images",
    "convert pdf to images",
    "reduce file size",
    "image optimization",
    "web image optimization",
    "fast pdf tools",
    "free pdf tools",
    "secure file converter",
    "local file processing",
  ],
  authors: [{ name: "JaeyGuides", url: "https://jaeyguides.com" }],
  metadataBase: new URL("https://jaeyguides.com"),
  applicationName: "JaeyGuides",
  openGraph: {
    title: "JaeyGuides — PDF & Image Utilities",
    description: "Fast, private, in-browser PDF and image tools.",
    type: "website",
    siteName: "JaeyGuides",
    locale: "en_US",
    url: "https://jaeyguides.com",
    images: [
      {
        url: ogImage.src,
        width: 1200,
        height: 630,
        alt: "JaeyGuides — PDF & Image Utilities",
      },
    ],
  },
  alternates: { canonical: "https://jaeyguides.com" },
  twitter: {
    card: "summary_large_image",
    title: "JaeyGuides — PDF & Image Utilities",
    description: "Fast, private, in-browser PDF and image tools.",
    images: [ogImage.src],
    // set your twitter handle if available
    site: "@jaeyguides",
    creator: "@jaeyguides",
  },
  icons: {
    icon: [
      { url: "/favicon.ico", rel: "icon", type: "image/x-icon" },
      { url: "/favicon.svg", rel: "icon", type: "image/svg+xml" },
      { url: faviconPng.src, rel: "icon", type: "image/png" },
    ],
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180" }],
    other: [{ rel: "manifest", url: "/site.webmanifest" }],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "noimageindex": false,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  // verification placeholders (Google/Bing/Ahrefs) - add actual codes in env or CI secrets
};